language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t bolwoy97/docker_course -f Dockerfile.dev .

script: 
  - docker run -e CI=true bolwoy97/docker_course npm run test -- --coverage

deploy:
  privider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker_test"
  env: "DockerTest-env"
  bucket_name: "elasticbeanstalk-eu-central-1-924906007858"
  bucket_path: "docker_test"
  on:
    branch: main

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
