language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t bolwoy97/docker_course -f Dockerfile.dev .

script: 
  - docker run -e CI=true bolwoy97/docker_course npm run test -- --coverage