FROM node:alpine
 
WORKDIR /app
COPY ./package.json ./
RUN npm install
#COPY . .

CMD ["npm", "run", "dev"]

# docker build -f Dockerfile.dev .
# docker run -it -p 3000:3000 CONTAINER_ID
# docker run -it -p 3000:3000 -v /app/node_modules -v ${pwd}:/app CONTAINER_ID
#where:
# -it to run interactive mode
# -p 3000:3000 to set ports
# -v $(pwd):/app to reference to files
# -v /app/node_modules to not reference to node_modules
