# docker-compose down && docker-compose up --build
version: '3'

services: 
  node_app: 
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "8080:8080"
    volumes: 
      - /app/node_modules
      - .:/app
  tests: 
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]

